name: team_vibrant_breakout
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flame: ^1.9.1
  get: ^4.6.6
  animate_do: ^3.1.2

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flame_audio: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^6.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    # /- images/a_dot_ham.jpeg
    - assets/images/player.png
    - assets/images/ball.png
    - assets/images/goldcoin.png
    - assets/images/wall.png
    - assets/images/diamond.png
    - assets/images/tile1.png
    - assets/images/tile2.png
    - assets/images/tile3.png
    - assets/images/tile4.png
    - assets/audio/gameover.mp3
    - assets/audio/hit.wav
    - assets/audio/shot.wav

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
