name: team_vibrant_breakout
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flame: ^1.9.1
  get: ^4.6.6
  animate_do: ^3.1.2

  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flame_audio: ^2.1.2
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  confetti: ^0.7.0
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0
  cloud_firestore: ^4.11.0
  audioplayers: ^5.2.0
  just_audio: ^0.9.35
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # google_fonts: ^6.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    # /- images/a_dot_ham.jpeg
    - assets/images/player.png
    - assets/images/ball.png
    - assets/images/goldcoin.png
    - images/imagbg.jpeg
    - images/breakout_bg.png
    - assets/images/wall.png
    - assets/images/diamond.png
    - assets/images/tile1.png
    - assets/images/tile2.png
    - assets/images/100.png
    - assets/images/fast.png
    - assets/images/life.png
    - assets/images/sparks.png
    - assets/images/tile3.png
    - assets/images/spark2.png
    - assets/images/tile4.png
    - assets/audio/gameover.mp3
    - assets/audio/gameover2.wav
    - assets/audio/hit.wav
    - assets/audio/shot.wav
    - assets/audio/block_hit.wav
    - assets/audio/level_complete.wav
    - assets/audio/level_music.wav
    - assets/audio/player_hit.wav

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DRAGON
      fonts:
        - asset: fonts/DRAGON-HUNTER.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: ARCADECLASSIC
      fonts:
        - asset: fonts/joystix monospace.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
