// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_SNPmw6cvT7MnrM3xHowtp-ikPw6F4xQ',
    appId: '1:510672289382:web:315f2a543709369363f7a7',
    messagingSenderId: '510672289382',
    projectId: 'brick-breakout',
    authDomain: 'brick-breakout.firebaseapp.com',
    storageBucket: 'brick-breakout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYsCTn7lBRULHYyMQe4X30d4-A3QE13Oc',
    appId: '1:510672289382:android:3bb8c92420eef66e63f7a7',
    messagingSenderId: '510672289382',
    projectId: 'brick-breakout',
    storageBucket: 'brick-breakout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADN1QkWmINNlewFMHAz_Jcu0ABrPvOqPc',
    appId: '1:510672289382:ios:371af22f25a29f3463f7a7',
    messagingSenderId: '510672289382',
    projectId: 'brick-breakout',
    storageBucket: 'brick-breakout.appspot.com',
    iosBundleId: 'com.example.teamVibrantBreakout',
  );
}
